common:
    lid_topic:  "/rslidar_points"
    imu_topic:  "/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 4      # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for RS-Bpearl LiDAR
    scan_line: 32
    scan_rate: 10      # only need to be set for velodyne and bpearl, unit: Hz,
    timestamp_unit: 3  # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond. TODO: What is an effect?
    blind: 2 # Maximum point distance from a LiDAR frame till points are weeding out TODO: Check, maybe it will be better after increasing

mapping:
    acc_cov: 0.0006771784583884886
    gyr_cov: 0.00013548849713483453
    b_acc_cov: 4.855592390728982e-06
    b_gyr_cov: 2.6867875817855036e-06
    fov_degree:    180
    det_range:     100.0 # Detection Range
    extrinsic_est_en:  false
    extrinsic_T: [ -0.13406141062872667, -0.010899820828818012, 0.006109253103427932]
    extrinsic_R: [ 0.9993809082422996, -0.003397272928783347, 0.03501797791768812,
                   -0.0036988105559615262, -0.9999566093030182, 0.008549755065630918,
                   0.03498741261178718, -0.0086739868491098, -0.9993501102771111]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
