common:
    lid_topic:  "/rslidar_points"
    imu_topic:  "/zed2/zed_node/imu/data_raw"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 4      # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for RS-Bpearl LiDAR
    scan_line: 32
    scan_rate: 10      # only need to be set for velodyne and bpearl, unit: Hz,
    timestamp_unit: 3  # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond. TODO: What is an effect?
    blind: 0.01 # Maximum point distance from a LiDAR frame till points are weeding out TODO: Check, maybe it will be better after increasing

mapping:
    acc_cov: 0.04641977329563476 # Discrete 0.9283954659126951 ; Contineous: 0.04641977329563476 TODO: Try discrete ones
    gyr_cov: 0.013213877349668923 # Discrete 0.26427754699337846; Contineous: 0.013213877349668923
    b_acc_cov: 0.0019703618139556927
    b_gyr_cov: 2.206282069791498e-05 # TODO: May it be in such a format?
    fov_degree:    180
    det_range:     260.0 # Detection Range
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
    # Fine
    extrinsic_T: [ -0.07964, -0.02023, -0.15070 ] # IMU is a base frame
    extrinsic_R: [ -0.02225, 0.08080, 0.99648,
                  -0.99786, 0.05948, -0.02710,
                  -0.06146, -0.99495, 0.07930 ]
    # Rough
    # extrinsic_T: [ -0.08425, -0.01959, -0.14716 ] # IMU is a base frame
    # extrinsic_R: [ 0.01670, 0.02366, 0.99958,
    #                -0.99980, -0.01032, 0.01694,
    #                0.01072, -0.99967, 0.02349 ]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
