common:
    lid_topic:  "/livox/lidar"
#    imu_topic:  "/livox/imu"
    imu_topic:  "/zed2/zed_node/imu/data_raw"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line:  6
    blind: 4

mapping:
#    acc_cov: 0.1
#    gyr_cov: 0.1
#    b_acc_cov: 0.0001
#    b_gyr_cov: 0.0001
    acc_cov: 0.0016
    gyr_cov: 0.000139626
    b_acc_cov: 0.0002509
    b_gyr_cov: 0.000033989
    fov_degree:    100
    det_range:     260.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
#    extrinsic_T: [ 0.05512, 0.02226, -0.0297 ]
#    extrinsic_R: [ 1, 0, 0,
#                   0, 1, 0,
#                   0, 0, 1]
#    extrinsic_T: [ 0.02450, −0.07146, −0.07405 ]
#    extrinsic_R: [ 0.99998, −0.00523, −0.00168,
#                   0.00523, 0.99999, 0.00119,
#                   0.00167, −0.00120, 1]
# Inversed:
    extrinsic_T: [ -0.02400, 0.07150, 0.07418 ]
    extrinsic_R: [ 0.99999, 0.00523, 0.00167,
                   -0.00523, 0.99998, -0.00120,
                   -0.00168, 0.00119, 1]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.